// Validation constants - These will be replaced by translation keys
export const VALIDATION_RULES = {
  EMAIL: {
    REQUIRED: "validation.emailRequired",
    INVALID: "validation.emailInvalid",
    PATTERN: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  },
  PASSWORD: {
    REQUIRED: "validation.passwordRequired",
    MIN_LENGTH: "validation.passwordMinLength",
    LOWERCASE: "validation.passwordLowercase",
    UPPERCASE: "validation.passwordUppercase",
    NUMBER: "validation.passwordNumber",
    CONFIRM_REQUIRED: "validation.confirmPasswordRequired",
    MISMATCH: "validation.passwordsMismatch",
  },
  CATEGORY: {
    NAME_REQUIRED: "validation.nameRequired",
    TYPE_REQUIRED: "validation.categoryTypeRequired",
  },
  ACCOUNT: {
    NAME_REQUIRED: "validation.nameRequired",
    NAME_MIN_LENGTH: "validation.nameMinLength",
    BALANCE_REQUIRED: "validation.balanceRequired",
    BALANCE_INVALID: "validation.balanceInvalid",
    BALANCE_POSITIVE: "validation.balancePositive",
    CURRENCY_REQUIRED: "validation.currencyRequired",
    TYPE_REQUIRED: "validation.accountTypeRequired",
  },
};

// API error messages - These will be replaced by translation keys
export const API_ERROR_MESSAGES = {
  NETWORK_ERROR: "errors.networkError",
  SERVER_CONNECTION_ERROR: "errors.serverConnectionError",
  INVALID_INPUT: "errors.invalidInput",
  EMAIL_EXISTS: "errors.emailExists",
  REGISTRATION_FAILED: "errors.registrationFailed",
  SERVER_ERROR: "errors.serverError",
  TIMEOUT_ERROR: "errors.timeoutError",
  TOKEN_INVALID: "errors.tokenInvalid",
  TOKEN_MISSING: "errors.tokenMissing",
  VERIFICATION_FAILED: "errors.verificationFailed",
  PASSWORD_RESET_FAILED: "errors.passwordResetFailed",
  USER_NOT_FOUND: "errors.userNotFound",
  INVALID_PASSWORD_REQUEST: "errors.invalidPasswordRequest",
  LOGIN_FAILED: "errors.loginFailed",
  INVALID_CREDENTIALS: "errors.invalidCredentials",
  REFRESH_TOKEN_FAILED: "errors.refreshTokenFailed",
  SESSION_EXPIRED: "errors.sessionExpired",
  UNAUTHORIZED: "errors.unauthorized",
  FETCH_CATEGORIES_FAILED: "errors.fetchCategoriesFailed",
  FETCH_CATEGORY_FAILED: "errors.fetchCategoryFailed",
  CREATE_CATEGORY_FAILED: "errors.createCategoryFailed",
  UPDATE_CATEGORY_FAILED: "errors.updateCategoryFailed",
  DELETE_CATEGORY_FAILED: "errors.deleteCategoryFailed",
  INVALID_CATEGORY_DATA: "errors.invalidCategoryData",
  CATEGORY_ALREADY_EXISTS: "errors.categoryAlreadyExists",
  CATEGORY_NOT_FOUND: "errors.categoryNotFound",
  CATEGORY_IN_USE: "errors.categoryInUse",
  FETCH_ACCOUNTS_FAILED: "errors.fetchAccountsFailed",
  FETCH_ACCOUNT_FAILED: "errors.fetchAccountFailed",
  CREATE_ACCOUNT_FAILED: "errors.createAccountFailed",
  UPDATE_ACCOUNT_FAILED: "errors.updateAccountFailed",
  DELETE_ACCOUNT_FAILED: "errors.deleteAccountFailed",
  INVALID_ACCOUNT_DATA: "errors.invalidAccountData",
  ACCOUNT_ALREADY_EXISTS: "errors.accountAlreadyExists",
  ACCOUNT_NOT_FOUND: "errors.accountNotFound",
  ACCOUNT_IN_USE: "errors.accountInUse",
  ACCOUNT_HAS_TRANSACTIONS: "errors.accountHasTransactions",
  ACCOUNT_GROUP_NOT_FOUND: "errors.accountGroupNotFound",
  ACCOUNT_GROUP_IN_USE: "errors.accountGroupInUse",
  DELETE_ACCOUNT_GROUP_FAILED: "errors.deleteAccountGroupFailed",
  CURRENCY_MISMATCH: "errors.currencyMismatch",
  FETCH_BUDGETS_FAILED: "errors.fetchBudgetsFailed",
  FETCH_BUDGET_FAILED: "errors.fetchBudgetFailed",
  CREATE_BUDGET_FAILED: "errors.createBudgetFailed",
  INVALID_BUDGET_DATA: "errors.invalidBudgetData",
  DELETE_BUDGET_FAILED: "errors.deleteBudgetFailed",
  UPDATE_BUDGET_FAILED: "errors.updateBudgetFailed",
  BUDGET_NOT_FOUND: "errors.budgetNotFound",
  BUDGET_IN_USE: "errors.budgetInUse",
  FETCH_SAVINGS_FAILED: "errors.fetchSavingsFailed",
  FETCH_SAVING_FAILED: "errors.fetchSavingFailed",
  CREATE_SAVING_FAILED: "errors.createSavingFailed",
  INVALID_SAVING_DATA: "errors.invalidSavingData",
  DELETE_SAVING_FAILED: "errors.deleteSavingFailed",
  UPDATE_SAVING_FAILED: "errors.updateSavingFailed",
  SAVING_NOT_FOUND: "errors.savingNotFound",
  SAVING_IN_USE: "errors.savingInUse",
};

// HTTP status codes
export const HTTP_STATUS = {
  CREATED: 201,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  CONFLICT: 409,
  NO_CONTENT: 204,
};
